"""Generate the folder data script and self-contained HTML, without dependencies.

Run from any directory: python path/to/Web/tools/build_offline.py
Use --skip-sources to rebuild distribution assets from the existing JSON files.
"""
from __future__ import annotations

import argparse
import base64
import json
import re
from html.parser import HTMLParser
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
WEB_ROOT = PROJECT_ROOT / "Web"
OFFLINE_ROOT = PROJECT_ROOT / "Offline"
OUTPUT_NAME = "马原研习社.html"
DATA_NAMES = ("questions", "subjective", "chapters", "banks")


class _ResourceAudit(HTMLParser):
    """Inspect actual HTML elements, not markup strings inside application JS."""
    def handle_starttag(self, tag: str, attrs: list) -> None:
        attrs = dict(attrs)
        if tag in ("script", "img") and attrs.get("src") and not attrs["src"].startswith("data:"):
            raise ValueError(f"The standalone HTML still references {attrs['src']}")
        if tag == "link" and attrs.get("rel") == "stylesheet":
            raise ValueError("The standalone HTML still references an external stylesheet")


def javascript_data(data: dict) -> str:
    # Escaping '<' prevents source text from ending an inline script element.
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    payload = payload.replace("<", "\\u003c").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    return "/* Generated by tools/build_offline.py; edit the source Markdown instead. */\nwindow.MAYUAN_DATA = " + payload + ";\n"


def read_web_asset(relative: str) -> str:
    path = (WEB_ROOT / relative).resolve()
    if not path.is_relative_to(WEB_ROOT.resolve()):
        raise ValueError(f"Asset outside Web: {relative}")
    return path.read_text(encoding="utf-8")


def standalone_html(html: str) -> str:
    def stylesheet(match: re.Match) -> str:
        relative = match.group(1)
        css = read_web_asset(relative)
        if re.search(r"</style", css, re.I):
            raise ValueError(f"Unsafe inline stylesheet: {relative}")
        return f"<style>\n/* {relative} */\n{css}\n</style>"

    def script(match: re.Match) -> str:
        relative = match.group(1)
        js = read_web_asset(relative)
        # A closing script tag inside JS strings/comments must stay literal JS.
        js = re.sub(r"</script", lambda m: "<\\/" + m.group(0)[2:], js, flags=re.I)
        return f"<script>\n/* {relative} */\n{js}\n</script>"

    html = re.sub(r'<link\s+rel="stylesheet"\s+href="([^"]+)"\s*>', stylesheet, html)
    html = re.sub(r'<script\s+src="([^"]+)"\s*></script>', script, html)
    image = WEB_ROOT / "assets" / "marx-engels.png"
    portrait = "data:image/png;base64," + base64.b64encode(image.read_bytes()).decode("ascii")
    # The homepage reuses the watermark src, so the PNG is embedded only once.
    html = html.replace('src="assets/marx-engels.png"', f'src="{portrait}"')
    _ResourceAudit().feed(html)
    return html


def build(regenerate: bool = True) -> Path:
    if regenerate:
        import parse_sources
        parse_sources.main()
    data = {name: json.loads((WEB_ROOT / "data" / f"{name}.json").read_text(encoding="utf-8"))
            for name in DATA_NAMES}
    for name in ("questions", "subjective", "banks"):
        if not isinstance(data[name], list):
            raise ValueError(f"Expected a list in {name}.json")
    if not isinstance(data["chapters"], dict) or not data["chapters"].get("children"):
        raise ValueError("The mind map must have a root and chapter branches")
    (WEB_ROOT / "data" / "offline-data.js").write_text(javascript_data(data), encoding="utf-8")
    html = standalone_html((WEB_ROOT / "index.html").read_text(encoding="utf-8"))
    OFFLINE_ROOT.mkdir(parents=True, exist_ok=True)
    output = OFFLINE_ROOT / OUTPUT_NAME
    output.write_text(html, encoding="utf-8")
    print("Folder version: Web/index.html")
    print(f"Single file: Offline/{OUTPUT_NAME} ({output.stat().st_size:,} bytes)")
    return output


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--skip-sources", action="store_true", help="Reuse existing data/*.json")
    args = parser.parse_args()
    build(regenerate=not args.skip_sources)
